2018-10-17 23:04:42,196 ERROR: Exception on /buy [POST] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 74, in buy
    user_buy = buy_stock(current_user=current_user, ticker_symbol=form.ticker_symbol.data, number_of_shares=form.number_of_shares.data)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 219, in buy_stock
    holding = get_holding(current_user, ticker_symbol)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 174, in get_holding
    if holding[0].ticker_symbol:
IndexError: list index out of range
2018-10-17 23:06:01,948 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-17 23:06:16,360 ERROR: Exception on /buy [POST] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 74, in buy
    user_buy = buy_stock(current_user=current_user, ticker_symbol=form.ticker_symbol.data, number_of_shares=form.number_of_shares.data)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 223, in buy_stock
    holding = get_holding(current_user, ticker_symbol)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 179, in get_holding
    return holding.number_of_shares
AttributeError: 'list' object has no attribute 'number_of_shares'
2018-10-17 23:06:25,495 ERROR: Exception on /buy [POST] [in /home/gene/.local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 74, in buy
    user_buy = buy_stock(current_user=current_user, ticker_symbol=form.ticker_symbol.data, number_of_shares=form.number_of_shares.data)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 223, in buy_stock
    holding = get_holding(current_user, ticker_symbol)
  File "/mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/routes.py", line 179, in get_holding
    return holding.number_of_shares
AttributeError: 'list' object has no attribute 'number_of_shares'
2018-10-17 23:07:07,012 INFO: WebTrader Startup [in /mnt/c/Users/Tyhebrewsaurus Rex/terminaltrader/app/__init__.py:50]
2018-10-18 18:18:21,763 INFO: WebTrader Startup [in /mnt/c/Users/GM/Desktop/webtrader/app/__init__.py:50]
2018-10-18 18:44:20,278 INFO: WebTrader Startup [in /mnt/c/Users/GM/Desktop/webtrader/app/__init__.py:50]
